"""Generate docs/configuration.md from the settings spec.

    python scripts/gen_settings_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

HEADER = """# Configuration reference

<!-- Generated by scripts/gen_settings_docs.py from fingerprint_attendance/conf.py. Do not edit. -->

Every setting resolves in this order:

1. `FINGERPRINT_ATTENDANCE = {...}` in your Django settings
2. an environment variable `FPA_<NAME>`
3. the default below

Environment values are cast to the setting's type:

| Type | Environment format |
|---|---|
| bool | `1/0`, `true/false`, `yes/no`, `on/off` |
| int / float | number |
| list | comma separated (`a,b`) or JSON array |
| int list | comma separated integers or JSON array |
| dict / json | JSON |
| duration | seconds (`90`), `90s`, `15m`, `2h`, `7d`, `1w`, `HH:MM:SS` or ISO 8601 |
| time | `HH:MM[:SS]` |
| path | dotted import path, or one of the listed aliases |

Nullable settings accept `none`/`null`/empty in the environment. Settings naming a class or
function take a dotted path, so you can swap in your own implementation. Values are validated
by Django system checks at startup (IDs `fpa.E0xx` / `fpa.W0xx`, see [System checks](checks.md)).
"""


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").replace("\t", "\\t")


def render() -> str:
    from fingerprint_attendance.conf import SETTINGS_SPEC

    out = [HEADER]
    groups: dict[str, list] = {}
    for spec in SETTINGS_SPEC:
        groups.setdefault(spec.group, []).append(spec)
    for group, specs in groups.items():
        out.append(f"\n## {group}\n")
        out.append("| Setting | Env var | Type | Default | Description |")
        out.append("|---|---|---|---|---|")
        for spec in specs:
            type_ = spec.type + (" (nullable)" if spec.nullable else "")
            desc = spec.description
            if spec.aliases:
                desc += " Aliases: " + ", ".join(f"`{a}`" for a in spec.aliases) + "."
            out.append(
                f"| `{spec.name}` | `{spec.env_var}` | {type_} | "
                f"`{_escape(spec.display_default())}` | {_escape(desc)} |"
            )
    return "\n".join(out) + "\n"


def main() -> None:
    path = ROOT / "docs" / "configuration.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
